version: '3'

services:
        db:
                image: postgres
        mq:
                image: rabbitmq
        web:
                build: .
                command: >
                        /bin/bash -c "rm -f /code/gedata/static/gedata/plots && ln -s /data/plots /code/gedata/static/gedata/plots &&
                                      python manage.py makemigrations && python manage.py migrate &&
                                      python manage.py runserver 0.0.0.0:8000"
                volumes:
                        - /data:/data
                ports:
                        - "8000:8000"
                depends_on:
                        - db
                        - mq
        worker:
                build: .
                command: >
                        /bin/bash -c "rm -f /code/gedata/static/gedata/plots && ln -s /data/plots /code/gedata/static/gedata/plots &&
                                      celery worker --app ge_data_manager --hostname=mq --broker "amqp://guest@mq" --loglevel=INFO --events"
                volumes:
                        - /data:/data
                depends_on:
                        - mq