version: '3'

services:
        db:
                image: postgres
        web:
                build: .
                command: >
                    /bin/bash -c "python manage.py migrate &&
                                  python manage.py runserver 0.0.0.0:8000"
                volumes:
                        - .:/code
                        - /home/mike/ge_data:/data
                ports:
                        - "8000:8000"
                depends_on:
                        - db
                        - mq

        mq:
                image: rabbitmq
